// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNj4wAwE_Sy4HVU7igh7lo6bl4ZXNYC8',
    appId: '1:466828508888:web:7c34c6da8c37ccb3bd61ad',
    messagingSenderId: '466828508888',
    projectId: 'teampay-be770',
    authDomain: 'teampay-be770.firebaseapp.com',
    storageBucket: 'teampay-be770.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8K04CCdsxh8r1PZMMgKWgUK_KjiWpzbE',
    appId: '1:466828508888:android:d702abbc94aab2c1bd61ad',
    messagingSenderId: '466828508888',
    projectId: 'teampay-be770',
    storageBucket: 'teampay-be770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvG-POJS3E8aG-lvbGfArP5ZEg8Uf_G3k',
    appId: '1:466828508888:ios:10b3dd305ad5f0dabd61ad',
    messagingSenderId: '466828508888',
    projectId: 'teampay-be770',
    storageBucket: 'teampay-be770.firebasestorage.app',
    iosBundleId: 'com.example.teampayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvG-POJS3E8aG-lvbGfArP5ZEg8Uf_G3k',
    appId: '1:466828508888:ios:10b3dd305ad5f0dabd61ad',
    messagingSenderId: '466828508888',
    projectId: 'teampay-be770',
    storageBucket: 'teampay-be770.firebasestorage.app',
    iosBundleId: 'com.example.teampayapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVNj4wAwE_Sy4HVU7igh7lo6bl4ZXNYC8',
    appId: '1:466828508888:web:968855117bc50212bd61ad',
    messagingSenderId: '466828508888',
    projectId: 'teampay-be770',
    authDomain: 'teampay-be770.firebaseapp.com',
    storageBucket: 'teampay-be770.firebasestorage.app',
  );
}
